git:
  depth: 1
language: python
python:
  - '3.6'
env:
  - PYTHONPATH="/opt/sublime_text"
install:
  - wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
  - echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
  - sudo apt-get update
  - sudo apt-get install -y sublime-text xvfb
  - pip3 install ruamel.yaml
  - mkdir -pv "/home/travis/.config/sublime-text-3/Packages/User" "/home/travis/.config/sublime-text-3/Installed Packages"
  - >
    echo '{ "installed_packages": ["YAML-Macros"] }' > "/home/travis/.config/sublime-text-3/Packages/User/Package Control.sublime-settings"
  - wget "https://packagecontrol.io/Package%20Control.sublime-package" -O "/home/travis/.config/sublime-text-3/Installed Packages"
script:
  - chmod +x ./script.sh
  - xvfb-run ./script.sh
